### ISSUE TITLE
Using "q" to close the notes.

### ISSUE THREAD

**Issue by otavioschwanck** [JellyApple102/flote.nvim#1]
Would be awesome to have a faster way to close the notes, like pressing "q" to save and close the notes

**Comment by JellyApple102** [comment]
Personally `:wq` is ingrained into my muscle memory so I didn't see a need to add any special window management.

That said, this plugin has gotten more attention than I thought it would so I may take the time to "pretty up" the plugin. Things like configuration and probably some better window management for the popup.

**Comment by JellyApple102** [comment]
Added 'q' to quit, as well as some basic window configuration. Closing issue.
