### ISSUE TITLE
Bug error running any command

### ISSUE THREAD

**Issue by lars-vc** [JellyApple102/flote.nvim#3]
![image](https://user-images.githubusercontent.com/57136208/231184004-a326eaf3-e52d-4df5-8902-8ab544b2dfc2.png)
I get this error when I run any of the commands. The files do get created in the ~/.cache/nvim/flote dir.

**Comment by JellyApple102** [comment]
What version of Neovim are you running? The Window title is only supported by the recent 0.9.0 release. You can disable the window title for older versions, check the README.

**Comment by lars-vc** [comment]
Ah that will be the issue. Sadly fedora doesn't have 0.9.0 yet. 
Thanks for the help!

**Comment by JellyApple102** [comment]
No problem, hopefully you can get updated soon.
