### ISSUE TITLE
add a default config

### ISSUE THREAD

**Issue by otavioschwanck** [JellyApple102/flote.nvim#4]
If calling setup with {} throws:

```
Error executing Lua callback: ...vio/.local/share/nvim/lazy/flote.nvim/lua/flote/init.lua:56: invalid key: title
stack traceback:
	[C]: in function 'nvim_open_win'
	...vio/.local/share/nvim/lazy/flote.nvim/lua/flote/init.lua:56: in function 'open_float'
	...vio/.local/share/nvim/lazy/flote.nvim/lua/flote/init.lua:73: in function <...vio/.local/share/nvim/lazy/flote.nvim/lua/flote/init.lua:70>
```

**Comment by JellyApple102** [comment]
Check your Neovim version. The window title requires 0.9.0, you can disable it. Check the README.

**Comment by JellyApple102** [comment]
Closing this and #5 as both are related to the window title. Calling `setup `does not open the floating window, I'm not sure why `setup` is throwing this error. Also seems related to #3, was solved by disabling the window title. If the issue persists, comment here again and we can figure it out.
